import { Question } from './types';

export const defaultQuestions: Question[] = [
  // --- TECH ---
  {
    id: 'Tech-20',
    category: 'Tech',
    points: 20,
    questionText: 'What does "AI" stand for in modern computing and technology?',
    answerText: 'Artificial Intelligence',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Tech-40',
    category: 'Tech',
    points: 40,
    questionText: 'Which programming language, originally named "Oak" by James Gosling in 1995, runs on billions of devices?',
    answerText: 'Java',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Tech-60',
    category: 'Tech',
    points: 60,
    questionText: 'Which neural network architecture, introduced in the 2017 paper "Attention Is All You Need", powers modern Large Language Models?',
    answerText: 'Transformer architecture',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Tech-80',
    category: 'Tech',
    points: 80,
    questionText: 'What was the name of the first general-purpose digital electronic computer, completed in 1945 at the University of Pennsylvania?',
    answerText: 'ENIAC (Electronic Numerical Integrator and Computer)',
    isCompleted: false,
    solvedByTeamId: null,
  },

  // --- SPORTS ---
  {
    id: 'Sports-20',
    category: 'Sports',
    points: 20,
    questionText: 'How many players from a single team are on the field at one time in a standard professional association football (soccer) match?',
    answerText: '11 players',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Sports-40',
    category: 'Sports',
    points: 40,
    questionText: 'In which global racket sport do national teams compete to win the prestigious "Davis Cup"?',
    answerText: 'Tennis',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Sports-60',
    category: 'Sports',
    points: 60,
    questionText: 'Who is the only cricketer in the history of the sport to score a milestone of 100 international centuries?',
    answerText: 'Sachin Tendulkar',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Sports-80',
    category: 'Sports',
    points: 80,
    questionText: 'In which European city were the first modern Olympic Games held in the year 1896?',
    answerText: 'Athens, Greece',
    isCompleted: false,
    solvedByTeamId: null,
  },

  // --- RAJAGIRI ---
  {
    id: 'Rajagiri-20',
    category: 'Rajagiri',
    points: 20,
    questionText: 'Rajagiri institutions are managed by the Carmelites of Mary Immaculate (CMI). Who is the holy founding saint of this congregation?',
    answerText: 'Saint Kuriakose Elias Chavara',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Rajagiri-40',
    category: 'Rajagiri',
    points: 40,
    questionText: 'What is the Latin motto of Rajagiri institutions, representing the core value of service to divinity and the nation?',
    answerText: '"Religioni et Patriae" (For God and Country)',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Rajagiri-60',
    category: 'Rajagiri',
    points: 60,
    questionText: 'In which two specific suburbs of Kochi, Kerala are the Rajagiri College of Social Sciences and the Rajagiri School of Engineering & Technology (RSET) respectively located?',
    answerText: 'Kalamassery and Kakkanad',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Rajagiri-80',
    category: 'Rajagiri',
    points: 80,
    questionText: 'In which year was Rajagiri College of Social Sciences established, marking the historical starting point of the modern Rajagiri educational brand?',
    answerText: '1955',
    isCompleted: false,
    solvedByTeamId: null,
  },

  // --- ENTERTAINMENT ---
  {
    id: 'Entertainment-20',
    category: 'Entertainment',
    points: 20,
    questionText: 'Which actor played the character of Tony Stark / Iron Man across the Marvel Cinematic Universe starting from 2008?',
    answerText: 'Robert Downey Jr.',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Entertainment-40',
    category: 'Entertainment',
    points: 40,
    questionText: 'Which biographical drama film, directed by Christopher Nolan, dominated the 2024 Academy Awards, winning Best Picture?',
    answerText: 'Oppenheimer',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Entertainment-60',
    category: 'Entertainment',
    points: 60,
    questionText: 'Who is the famous Indian composer who won two Oscars in 2009 for the soundtrack and original song "Jai Ho" from Slumdog Millionaire?',
    answerText: 'A. R. Rahman',
    isCompleted: false,
    solvedByTeamId: null,
  },
  {
    id: 'Entertainment-80',
    category: 'Entertainment',
    points: 80,
    questionText: 'What was the title of the very first feature-length cel-animated movie ever released, produced by Walt Disney in 1937?',
    answerText: 'Snow White and the Seven Dwarfs',
    isCompleted: false,
    solvedByTeamId: null,
  },
];
